const applicationJson = 'application/json';

export const DEFAULT_HEADERS = {
  Accept: applicationJson,
  // eslint-disable-next-line @typescript-eslint/naming-convention
  'Content-Type': applicationJson,
};

export const MESSAGE_RESPONSE_KEYS: Record<string, string> = {
  INVALID_USERNAME_OR_PASSWORD: 'USERNAME ATAU PASSWORD SALAH',
  USER_LOGIN_NOT_FOUND: 'USER LOGIN TIDAK DITEMUKAN',
  USER_NOT_FOUND: 'USER TIDAK DITEMUKAN',
  FAILED_TO_REGISTER_USER: 'REGISTER USER GAGAL',
  PHONE_ALREADY_CONFIRMED: 'NO. HANDPHONE SUDAH TERKONFIRMASI',
  INVALID_PHONE_NUMBER: 'NOMOR TELEPON TIDAK VALID',
  INVALID_OTP_NUMBER: 'NOMOR OTP TIDAK VALID',
  FAILED_TO_RESET_PASSWORD: 'RESET PASSWORD GAGAL',

  INVALID_DATA: 'DATA TIDAK VALID',
  DATA_NOT_FOUND: 'DATA TIDAK DITEMUKAN',
};
